Traceback (most recent call last):
  File "/home/w3p/anaconda3/envs/set6-py39/lib/python3.9/site-packages/ombott/ombott.py", line 276, in _handle
    return self.handler(self, route, kwargs, route_hooks, error404_405)
  File "/home/w3p/anaconda3/envs/set6-py39/lib/python3.9/site-packages/ombott/ombott.py", line 242, in handler
    return partial_hook(hook_route, extra['param_values'])
  File "/home/w3p/myp4wgit/facep4w/_main_router/__init__.py", line 113, in url_not_found
    ombott.response.headers["Location"] = Router(route, params).location
  File "/home/w3p/myp4wgit/facep4w/_main_router/__init__.py", line 68, in __init__
    r_lst = {e["rule"].split('/', 1)[1] for e in Reloader.ROUTES}
  File "/home/w3p/myp4wgit/facep4w/_main_router/__init__.py", line 68, in <setcomp>
    r_lst = {e["rule"].split('/', 1)[1] for e in Reloader.ROUTES}
TypeError: string indices must be integers


